# Generated by Django 2.2.7 on 2019-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingboard',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
