# Generated by Django 2.2.7 on 2019-11-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBoard',
            fields=[
                ('landboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landBoard.LandBoard')),
                ('purpose', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('landBoard.landboard',),
        ),
        migrations.CreateModel(
            name='SharingBoard',
            fields=[
                ('landboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landBoard.LandBoard')),
                ('land_img', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('landBoard.landboard',),
        ),
    ]
