# Generated by Django 2.2.7 on 2019-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0002_requestboard_sharingboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landboard',
            name='recruitment_status',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집마감', '모집마감')], max_length=30),
        ),
        migrations.AlterField(
            model_name='landboard',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('세종', '세종'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], max_length=100),
        ),
        migrations.AlterField(
            model_name='landboard',
            name='sharing_term',
            field=models.CharField(choices=[('하루', '하루'), ('일주일 이내', '일주일 이내'), ('1년', '1년'), ('3년', '3년'), ('5년', '5년')], max_length=100),
        ),
    ]
