# Generated by Django 2.2.7 on 2019-11-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0002_land_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_request',
            name='is_completed',
        ),
    ]
