# Generated by Django 2.2.7 on 2019-11-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0003_auto_20191123_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landboard',
            name='recruitment_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='landboard',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='landboard',
            name='sharing_term',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sharingboard',
            name='land_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
