# Generated by Django 2.2.7 on 2019-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0004_auto_20191123_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
