# Generated by Django 2.2.7 on 2019-11-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landBoard', '0005_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landboard',
            name='is_free',
            field=models.CharField(max_length=100),
        ),
    ]
