# Generated by Django 2.2.7 on 2019-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='region_filter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
