# Generated by Django 2.2.7 on 2019-11-23 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otherBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
