# Generated by Django 2.2.7 on 2019-11-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_recruitment_board',
            new_name='Join',
        ),
        migrations.RenameModel(
            old_name='Successful_case_board',
            new_name='Review',
        ),
    ]
