# Generated by Django 2.2.7 on 2019-11-29 18:43

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('otherBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to='picture/'),
        ),
    ]
