# Generated by Django 2.2.7 on 2019-11-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otherBoard', '0002_auto_20191123_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Successful_case_board',
        ),
        migrations.RenameModel(
            old_name='Join',
            new_name='Team_recruitment_board',
        ),
    ]
