# Generated by Django 2.2.7 on 2019-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherBoard', '0003_auto_20191123_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='active_period',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
