# Generated by Django 2.2.7 on 2019-11-23 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otherBoard', '0005_auto_20191123_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Profile_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='join',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='Profile_scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
