# Generated by Django 2.1.8 on 2019-11-23 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otherBoard', '0006_auto_20191123_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='like',
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Profile_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
