# Generated by Django 2.2.7 on 2019-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealboard',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date published'),
        ),
        migrations.AddField(
            model_name='questionboard',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date published'),
        ),
    ]
