# Generated by Django 2.2.7 on 2019-11-29 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('additionBoard', '0002_db_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealboard',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Deal_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
