# Generated by Django 2.2.7 on 2019-11-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
