# Generated by Django 2.2.7 on 2019-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='detailAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='postcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='roadAddress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
