# Generated by Django 2.2.7 on 2019-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_land_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
