# Generated by Django 2.2.7 on 2019-11-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Land',
        ),
    ]
